### ISSUE TITLE
Syntax error on typed properties in PHP < 7.4

### ISSUE THREAD

**Issue by LCinHK** [AlexanderOMara/flarum-gravatar#1]
Flarum encountered a boot error (ParseError)
syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST)
thrown in vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 21

**Comment by AlexanderOMara** [comment]
Darn, looks like typed properties is a PHP 7.4+ feature. You must be using a version of PHP older than that.

I'll have to go through and remove the type information, at-least until Flarum drops PHP 7.2 and 7.3 support.

**Comment by AlexanderOMara** [comment]
Fixed in version 1.0.1
