### ISSUE TITLE
Undefined variable: key

### ISSUE THREAD

**Issue by Freenex1911** [AlexanderOMara/flarum-gravatar#6]
It looks like the extension works but I still get the following errors in logs:

`flarum_1  | 2021/04/11 13:47:35 [error] 779#779: *4977 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: key in /opt/flarum/vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 60" while reading response header from upstream, client: 87.X.X.X, server: , request: "GET /api/users/3 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm7.sock:", host: "flarum.example.com", referrer: "https://flarum.example.com/"
flarum_1  | 2021/04/11 13:47:35 [error] 779#779: *4979 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: key in /opt/flarum/vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 60PHP message: PHP Notice:  Undefined variable: key in /opt/flarum/vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 60PHP message: PHP Notice:  Undefined variable: key in /opt/flarum/vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 60PHP message: PHP Notice:  Undefined variable: key in /opt/flarum/vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 60PHP message: PHP Notice:  Undefined variable: key in /opt/flarum/vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 60PHP message: PHP Notice:  Undefined variable: key in /opt/flarum/vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 60PHP message: PHP Notice:  Undefined variable: key in /opt/flarum/vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 60PHP message: PHP Notice:  Undefined variable: key in /opt/flarum/vendor/alexanderomara/flarum-gravatar/src/Extenders/BasicUserSerializing.php on line 60" while reading response header from upstream, client: 87.X.X.X, server: , request: "GET /api/discussions?include=user%2ClastPostedUser%2Ctags%2CfirstPost&sort&page%5Boffset%5D HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm7.sock:", host: "flarum.example.com", referrer: "https://flarum.example.com/"
`

**Comment by AlexanderOMara** [comment]
Good catch, minor mistake while refactoring.

Fixed in 1.3.1
