### ISSUE TITLE
Cannot be installed with Flarum 1.0.0

### ISSUE THREAD

**Issue by hschneider66** [AlexanderOMara/flarum-gravatar#9]
Trying to install throws the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires alexanderomara/flarum-gravatar ^1.4 -> satisfiable by alexanderomara/flarum-gravatar[1.4.0].
    - alexanderomara/flarum-gravatar 1.4.0 requires flarum/core ^0.1.0-beta.16 -> found flarum/core[v0.1.0-beta.16] but it does not match your minimum-stability.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by AlexanderOMara** [comment]
I've just released version 1.5.0 which is compatible with Flarum ^1.0.0, and should solve this.

Let me know if you still have issues.

**Comment by hschneider66** [comment]
Works like a charm. Thanks!
